# Generated by Django 6.1.1 on 2026-09-12 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payment_success', 'Payment Success'), ('activation', 'Subscription Activation'), ('expiry_warning', 'Expiry Warning'), ('fare_change', 'Fare Change'), ('rollover_extension', 'Rollover Extension'), ('shift_started', 'Route Shift Started'), ('shift_reverted', 'Route Shift Reverted'), ('shift_payment_required', 'Shift Payment Required')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
