# Generated by Django 6.1.1 on 2026-09-11 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('qr_token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('switched', 'Switched')], default='active', max_length=20)),
                ('shift_count', models.PositiveSmallIntegerField(default=0)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.plantype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('reverted', models.BooleanField(default=False)),
                ('extra_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('original_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_originals', to='companies.route')),
                ('temporary_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_temporaries', to='companies.route')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='subscriptions.subscription')),
            ],
        ),
    ]
