# Generated by Django 6.0.8 on 2026-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('payment_failed', 'Payment failed'), ('active', 'Active'), ('expired', 'Expired'), ('switched', 'Switched')], default='active', max_length=20),
        ),
    ]
