# Generated by Django 6.1.1 on 2026-09-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='commission_rate',
        ),
    ]
