# Generated by Django 6.0.8 on 2026-09-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_route_destination_lat_route_destination_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fare',
            name='evening_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
